### ISSUE TITLE
Not working in VScode v1.63.2

### ISSUE THREAD

**Issue by rohantarai** [zytjs/classNameToCss#10]
- className from .jsx file is not showing in css file.
- Let me know if my approach is wrong.

![image](https://user-images.githubusercontent.com/16543074/148523874-6a79812a-745a-451b-b5dc-6072e946124d.png)

![image](https://user-images.githubusercontent.com/16543074/148523950-629715a3-0ddb-4ec8-8d7a-3b9a842781bf.png)

**Comment by zitup** [comment]
It's strange, i just update my vs code to 1.63.2, it works well.

FYI, extension version is v0.0.6, os is Mac.

**Comment by rohantarai** [comment]
![image](https://user-images.githubusercontent.com/16543074/148553650-cdead6a4-f771-4046-9173-98a86900bab3.png)

- Can you confirm if the extension works in Windows 10 and VScode v1.63.2?
- i found this extension to be working in windows 10 and vscode 1.63.2 (https://marketplace.visualstudio.com/items?itemName=zenghongtu.vscode-css-intellisense)

**Comment by zitup** [comment]
Windows does not work well, i just tested it on mac os. I think the different is Mac os use `/`, window use `\` in file path, i will fix it and make it work well on Window.

**Comment by rohantarai** [comment]
@zitup hey thanks. Looking forward to use it in windows!

**Comment by zitup** [comment]
@rohantarai You can use it in windows now
