### ISSUE TITLE
Please add support for IDs

### ISSUE THREAD

**Issue by YanikKendler** [zytjs/classNameToCss#14]
I and many other often give a major parent element a ID and then access child classes or element names using the ID of the parent. So it would be great to have autocomplete for those IDs as well. Thank u

**Comment by zitup** [comment]
sry, that featuer is not a scope of this extension

**Comment by YanikKendler** [comment]
> sry, that featuer is not a scope of this extension

why exactly.. isnt this extention ment for better code completion in css, isnt it even the same logic for classes and ids?
