### ISSUE TITLE
提示css类名时，会多一个点

### ISSUE THREAD

**Issue by zhoufenfens** [zytjs/classNameToCss#3]
例如 输入 .test，然后选择提示内容，最终页面上的是 ..test ,多一个点，这个能优化下么

**Comment by zitup** [comment]
我在mac下没发现这个问题，你是什么系统？vs code的版本是多少？

**Comment by zhoufenfens** [comment]
> 我在mac下没发现这个问题，你是什么系统？vs code的版本是多少？

我也是mac, vscode版本是1.42.0

**Comment by zitup** [comment]
升级了下vs code，在scss和less文件没发现问题，具体是怎么使用，比如是否vue文件

**Comment by zhoufenfens** [comment]
> 升级了下vs code，在scss和less文件没发现问题，具体是怎么使用，比如是否vue文件

我是在.vue文件里，用的scss写的样式。
例如我想输入.test, 当键入.t 的时候，下面就会提示.test,选了test, 页面上的页面就变成 ..test, 冗余了一个.

**Comment by zitup** [comment]
我测试一下

**Comment by zitup** [comment]
![image](https://user-images.githubusercontent.com/12710516/74758585-80654c00-52b2-11ea-9df9-b471016eabf0.png)

不知道为什么 vue 提示有两份一样的，还要再看一下，你那也是这样吗？

**Comment by zitup** [comment]
提示两份好像是vscode是我安装了vuetr的原因，貌似他也会提示class，以
![image](https://user-images.githubusercontent.com/12710516/74761468-0edbcc80-52b7-11ea-9877-c72e04885f62.png)
的形式，vue开发应该有安装vuetr吧？我的这个插件应该用不到了，考虑后续去掉vue的支持了
