### ISSUE TITLE
vue中使用回车或者鼠标点击输入之后会多一个点

### ISSUE THREAD

**Issue by tinyTea** [zytjs/classNameToCss#6]
<img width="528" alt="image" src="https://user-images.githubusercontent.com/10094840/88127164-9ed6c700-cc05-11ea-9e77-17a044d6056b.png">
回车或鼠标选择输入后：
<img width="264" alt="image" src="https://user-images.githubusercontent.com/10094840/88127180-ab5b1f80-cc05-11ea-93cd-fad7994f81f9.png">

**Comment by zitup** [comment]
这个是已知问题，已经解决了，今天会发布一个新版本～

**Comment by zitup** [comment]
@tinyTea 已发布，确认没问题之后，可以关闭此 issue～
